from pathlib import Path

path = Path('src/i18n.tsx')
text = path.read_text()
anchor = "  'Archivos Temporales del Sistema': 'System Temporary Files',\n"
if anchor not in text:
    raise SystemExit('Missing backend translation anchor')
additions = """  'Caché de Shaders de DirectX': 'DirectX Shader Cache',
  'Archivos temporales generados por Windows y servicios en segundo plano dentro de C:\\\\Windows\\\\Temp.': 'Temporary files generated by Windows and background services inside C:\\\\Windows\\\\Temp.',
  'Purgio intentará eliminar únicamente entradas que superen las protecciones de rutas críticas, symlinks y reparse points. Archivos en uso pueden conservarse.': 'Purgio will attempt to remove only entries that pass critical-path, symlink, and reparse-point protections. Files in use may be kept.',
  'Revisar antes de eliminar; no se selecciona automáticamente.': 'Review before removing; this item is not selected automatically.',
  'Bases de datos thumbcache_*.db que Windows Explorer usa para acelerar vistas previas.': 'thumbcache_*.db databases used by Windows Explorer to speed up previews.',
  'Solo se eliminarán las bases de miniaturas mostradas en el Cleanup Plan. Windows puede regenerarlas cuando vuelvas a explorar carpetas.': 'Only the thumbnail databases shown in the Cleanup Plan will be removed. Windows can regenerate them when you browse folders again.',
  'Seguro de eliminar; las miniaturas se reconstruyen bajo demanda.': 'Safe to remove; thumbnails are rebuilt on demand.',
  'Shaders compilados almacenados temporalmente por DirectX para reducir trabajo repetido de la GPU.': 'Compiled shaders stored temporarily by DirectX to reduce repeated GPU work.',
  'Se liberará el almacenamiento temporal detectado. Juegos y aplicaciones pueden recompilar shaders cuando vuelvan a ejecutarse.': 'Detected temporary storage will be freed. Games and applications may recompile shaders the next time they run.',
  'Seguro de eliminar; Windows y las aplicaciones recrean la caché cuando es necesaria.': 'Safe to remove; Windows and applications recreate the cache when needed.',
"""
if "  'Caché de Shaders de DirectX': 'DirectX Shader Cache',\n" not in text:
    text = text.replace(anchor, anchor + additions, 1)
path.write_text(text)
