name: "Publicar Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""
          - platform: "macos-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: "Clonar Repositorio"
        uses: actions/checkout@v4

      - name: "Instalar Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: "Instalar Rust stable"
        uses: dtolnay/rust-toolchain@stable

      - name: "Instalar dependencias de Linux (Ubuntu)"
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: "Instalar dependencias del proyecto"
        run: npm install

      - name: "Compilar y Publicar en GitHub Releases"
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Purgio v${{ github.ref_name }}"
          releaseBody: "Vea el CHANGELOG.md para obtener detalles de los cambios en esta versión."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
